### ISSUE TITLE
Spreadsheet 2.0.0 - Error when typing percent cells

### ISSUE THREAD

**Issue by Legioth** [vaadin/spreadsheet#557] opened 2017-06-09 05:24 UTC
@fgrazi commented on [Thu Jun 08 2017](https://github.com/vaadin/framework/issues/9502)

I tried to enter percent cells in the spreadsheet. I typed:
  - "19" - Just fine the cell became 19.00
  - "19%" - OK again, acceptes as 19.00%
  - "19" - (no percent again): got 1900% instead of 19.99

Apparently after the first entry concluded by a percent sign all typed cells are assumes as percentage.

**Comment by Peppe** [comment] 2017-06-19 07:37
Hi @fgrazi. I'm sorry that you are having troubles with Vaadin Spreadsheet.

I assume that it is a typo in the description that you got 19.99 and that it should say that you got 19.00. I'll go forward with that assumption.

I tested out what you described in native Excel as well. What I found was that it works exactly like you described there - if you type a number without sign to a field marked as a percentage field, then Excel will add two zeroes and a percent sign after (19 -> 1900%). Gif of the behaviour below.

![vaadin-spreadsheet-percent](https://user-images.githubusercontent.com/525503/27274207-1eb29e18-54db-11e7-836b-44205d01b2c2.gif)

As Excel works this way, I'm hesitant to make changes - we would be further away to work in the same way as the industry patterns. 

There is an separate issue here however - that we have no feature to change manually the format of a cell. That makes it tricky to change the format from percentage back to number. Having a toolbar in Spreadsheet would be a great new feature and it could provide a lot of tools. One workaround that can be used today is copying over the cell with another which is in general format. Then the cell will also be that and you can type in 19 normally.

I'm closing down this issue as I see it as intended behaviour. Please reopen if you want to share your thoughts further on this.

**Comment by alvarezguille** [comment] 2017-06-19 08:44
The behavior for a single cell seems to be fine, and according to the excel behavior.

But I actually think the issue is still valid.

As @fgrazi said:
>Apparently after the first entry concluded by a percent sign all typed cells are assumes as percentage.

So it seems to be affecting all cells that have the default style and that's an issue (IMO).

This can be tested in the [demo](https://demo.vaadin.com/spreadsheet/):
* open the formatting demo
* type 19% in A8 -> you get “19.00%”
* type 19 in A9  -> you get “1900.00%”

**Comment by fgrazi** [comment] 2017-06-19 08:53
Exactly as alvarezguille  commented (and as I explained). The problem is not the first cell, the problem are the cells typed after the first! Worst: there is no way to reset, I can't even offer a bypass to the user. If the user by mistake types a percent there is no way to cancel the miss-assumed behaviour. Using percent cells is quite common in spreadsheet, in fact I detected the error in my first Vaadin spreadsheet trial. I date to understand how this issue was still unknown. Can you please reopen the issue?

**Comment by fgrazi** [comment] 2017-06-19 08:58
P.S. Peppe says "I'm closing down this issue as I see it as intended behaviour. Please reopen if you want to share your thoughts further on this.". **I cant' do it under GitHub policy**. You shall do it.

**Comment by Peppe** [comment] 2017-06-19 10:56
Sorry for that. You are right. The issue is now reopened-

**Comment by alvarezguille** [comment] 2017-06-19 12:02
I added a possible solution for this issue in #564. In particular it's fixing the case when a percentage cell affects how the value is formatted in other cells.
It's not adding a way to remove the percentage formatting from Spreadsheet UI, Current behavior seems to match Excel, if that's still important I think a separate issue should be created.

**Closed** 2017-07-17 11:30 UTC
