### ISSUE TITLE
Unable to paste in to Spreadsheet

### ISSUE THREAD

**Issue by lpereirafernandez** [vaadin/spreadsheet#706] opened 2019-07-04 10:00 UTC
Hi there,

We have recently upgraded from Vaadin 7.6.5 and Spreadsheet 1.2.2 to Vaadin 8.8.2 and Spreadsheet 2.1.0 and we have noticed that now we are not able to paste data in to a spreadsheet as we could before the upgrade.

Many thanks,
Luis

**Comment by alvarezguille** [comment] 2019-07-08 09:56
This can be verified in [spreadsheet demo](https://demo.vaadin.com/spreadsheet/) in some demos like `Formatting` paste doesn't seem to work. Needs to be investigated

**Comment by lpereirafernandez** [comment] 2019-07-08 10:40
We don't use formatting just something as simple as:

```
Spreadsheet embeddedSpreadsheet = new Spreadsheet(myByteArrayInputStream);
embeddedSpreadsheet.setSheetSelectionBarVisible(false);
```

With that simple configuration, with version 1.2.2 it was perfectly possible to paste content. With no additional change but the upgrade to version 2.1.0, now we are not able to paste content.

Any ideas?

**Comment by lpereirafernandez** [comment] 2019-07-25 09:11
Hi @alvarezguille, have you been able to take a look at this?

Our customers keep on complaining about this unexpected behavior change.

**Comment by lucailmartini** [comment] 2019-07-26 09:31
Hi, is there a plan to fix this issue?
This seems to be a regression that is worth investigating and fixing.
We recently updated from version 2.0.1 to 2.1.0 to get the POI v.317 due to security reasons and we can confirm that copy and paste was previously working in 2.0.1

**Comment by alvarezguille** [comment] 2019-07-26 09:32
We are looking into it, sorry for the delay without answers.

**Comment by lucailmartini** [comment] 2019-07-26 09:46
I have seen that the current master incorporates POI 4. Will this issue be fixed in a version that is still on POI 3.17?

**Comment by alvarezguille** [comment] 2019-07-26 09:51
While testing in our different demos and test UIs we noticed that adding the Spreadsheet to a Panel allows copying and pasting in the Spreadsheet.

Can you test if this helps workaround the issue as a temporary solution while we investigate it further?

This regression between 2.0 and 2.1 will be fixed in a maintenance release of 2.1 with POI 3.17

**Comment by lucailmartini** [comment] 2019-07-26 14:15
I can confirm that inserting the spreadsheet component inside a Panel is a viable workaround.

**Comment by lpereirafernandez** [comment] 2019-07-26 17:07
Yes, it also works for us.

**Closed** 2019-08-05 06:43 UTC

**Comment by DiegoCardoso** [comment] 2019-08-05 15:02
Spreadsheet **2.1.1** released with this fix.
