### ISSUE TITLE
Conditional formatting disables the formula evaluation

### ISSUE THREAD

**Issue by kiaruska** [vaadin/spreadsheet#667] opened 2018-07-04 15:58 UTC
The issue is related to conditional formatting and formulas evaluation.
We have attached a sample where we have reproduced the case.

To reproduce the problem, follow these steps:

    Change the value of cell "A2" from '2018/07 to '2018/05
    The cell F2 is not revaluated from the spreadsheet

The problem seems caused by a chain of dependencies:

The color of B2 depends from the value of H2
The value of H2 depends from the value of F2
The value of F2 depends from the value of A2

If we broke the double redirection (if B2 depends directly from A2 and F2 depends from A2 too), the problem doesn't rise anymore.

[Evaluation_formula_issue.xlsx](https://github.com/vaadin/spreadsheet/files/2163789/Evaluation_formula_issue.xlsx)

**Comment by kiaruska** [comment] 2018-07-23 15:08
Thanks for the planification of the issue analysis.
We would need the fix on 1.4 version.
If you need more information about the issue, you can ask me.

**Comment by alvarezguille** [comment] 2018-08-14 15:41
Hi @kiaruska

We have been checking this issue. It looks like a duplicate of #576.

This could be fixed by updating to POI 3.17, but last time we checked it caused some regressions, that's why we need to be careful about it, we're checking those regressions at the moment.

**Comment by alvarezguille** [comment] 2018-08-28 13:38
We have concluded that this issue should be fixed by upgrading POI version to 3.17.
As it was mentioned before POI 3.17 caused a regression with some cases of conditional formatting [61761](https://bz.apache.org/bugzilla/show_bug.cgi?id=61761) and [61764](https://bz.apache.org/bugzilla/show_bug.cgi?id=61764)
This change will be released in new minor versions of Spreadsheet, version compatible with Vaadin Framework 7 will be 1.5 and the regression will be clarified in release notes and documentation.
@kiaruska is this regression something that would prevent from using Spreadsheet 1.5? Any comment about suggested solution?

**Comment by kiaruska** [comment] 2018-08-29 08:58
Hi @alvarezguille ,
what are the regressions that will be introduced?
The issues 61761 and 61764 are closed.
I followed the thread #648 but this is about 3.17 beta version.
If there aren't others known regressions, I haven't observations about the POI updating.
Thanks
Chiara

**Comment by alvarezguille** [comment] 2018-08-29 10:33
61761 and 61764 are the regressions which are closed but not included in 3.17 final, according to the comment in [61761](https://bz.apache.org/bugzilla/show_bug.cgi?id=61761#c0) the fix will be part of 4.0.x.

**Comment by kiaruska** [comment] 2018-08-29 12:28
I see, thanks.
I agree with your proposal to release a new minor versions of Spreadsheet, version compatible with Vaadin Framework 7, clarifying the regressions in release notes and documentation.

**Comment by tulioag** [comment] 2018-09-06 16:03
Spreadsheet 1.5.0.alpha1 is released https://github.com/vaadin/spreadsheet/releases/tag/1.5.0.alpha1. 

@kiaruska, please test it and let us know if you have issues.

**Closed** 2018-09-06 16:04 UTC
